```{r}
mushrooms<-read.csv("C:/Users/harshil/Desktop/mushrooms.csv")
```


```{r}
library(rpart)
library(caret)
library(rpart.plot)
library(rattle)
library(readxl)
```


```{r}
str(mushrooms)
```


```{r}
nrow(mushrooms) - sum(complete.cases(mushrooms))
```
```{r}
mushrooms$veil.type <- NULL
```

```{r}

table(mushrooms$class,mushrooms$odor)
number.perfect.splits <- apply(X=mushrooms[-1], MARGIN = 2, FUN =function(col){
t <- table(mushrooms$class,col)
sum(t == 0)
})
```


```{r}
# Descending order of perfect splits
order <- order(number.perfect.splits,decreasing = TRUE)
number.perfect.splits <- number.perfect.splits[order]
```


```{r}
 #Plot graph
par(mar=c(10,2,2,2))
barplot(number.perfect.splits,
main="Number of perfect splits vs feature",
xlab="",ylab="Feature",las=2,col="wheat")
```


```{r}
set.seed(12345)
train <- sample(1:nrow(mushrooms),size =ceiling(0.80*nrow(mushrooms)),replace = FALSE)
# training set
mushrooms_train <- mushrooms[train,]
# test set
mushrooms_test <- mushrooms[-train,]
```


```{r}
penalty.matrix <- matrix(c(0,1,10,0), byrow=TRUE, nrow=2)
# building the classification tree with rpart
tree <- rpart(class~.,
data=mushrooms_train,
parms = list(loss = penalty.matrix),
method = "class")
```


```{r}
rpart.plot(tree, nn=TRUE)
```


```{r}
# choosing the best complexity parameter "cp" to prune the tree
cp.optim <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]
# tree prunning using the best complexity parameter. For more in
tree <- prune(tree, cp=cp.optim)
```

```{r}
pred <- predict(object=tree,mushrooms_test[-1],type="class")
#Calculating accuracy
t <- table(mushrooms_test$class,pred)
confusionMatrix(t)

```

